### PR TITLE
Fix nautobot php

### PR DESCRIPTION
**Pull request by Mocem1**
Fix a few typo's

### CODE REVIEW

**Comment by davekempe** [comment]
@Mocem1 what happened here? I was asleep. I'm interested in supporting nautobot!

**Comment by davekempe** [comment]
hey @Mocem1 that link is broken unfortunately. If you want to maintain a fork, you are welcome to! If you want to work with us and make this module work for both, we are open to that too. We don't use Nautobot as much as Netbox, but we would love to get more into it.

**Comment by Mocem1** [comment]
Hi @davekempe, 

I would be happy to assist maintaining although I'm not a php developer. Personally I think It will become more and more difficult to make 1 module for Nautobot and Netbox. I would not be surprised if there will be more breaking changes quite soon. 

For now in case of major changes of the Nautobot API I can always ask the php devs from the company I work for.

**Comment by sol1-matt** [comment]
Hi @Mocem1, 

I do most of the coding on this module and I'm not a PHP dev, I based this module on and existing one and made small changes over time to it.  If you have basic scripting knowledge you should be able to maintain a Nautobot fork of this module.

I'm not sure on the direction of Nautobot in terms of maintaining compatibility with Netbox but you are likely right that a Netbox import module and Nautobot import module will have unique changes over time.

Having said that they are likely to have a lot of commonality so I'd be comfortable collaborating with you on ensuing the Netbox Import Module and Nautobot Import Module are maintained in a compatible fashion and features common to both systems are migrated between the 2 modules.

**Pull request closed without merging**
